### ISSUE TITLE
Windows installer coming from cache does not complete in 360 minutes

### ISSUE THREAD

**Issue by gcarreno** [gcarreno/setup-lazarus#16]
After implementing caching for the installer files, looks like the cached windows executable gets somehow damaged or altered that it now does not complete the installation and hangs for at least the 360 minutes allotted by GitHub actions.

I don't even know how to start debugging this one!

**Comment by pashagolub** [comment]
yes, we have a problem as well https://github.com/cybertec-postgresql/pg_timetable_gui/actions/runs/3788520450/jobs/6441378111

**Comment by gcarreno** [comment]
Hey Y'all

I'm hoping that the last Pull Request that I merged from @ZhymabekRoman has resolved this issue!!

I'll need to confirm, but I also need to update the current Stable version, since I've been lazy and postponed it.

Cheers,
Gus

**Comment by ZhymabekRoman** [comment]
@gcarreno, thank you, I did not set out to fix this problem, but it seems to me that perhaps it should be solved. Can you please check?

**Comment by gcarreno** [comment]
Hey Zhymabek (@ZhymabekRoman),

> thank you

You are more than welcome!!

>  I did not set out to fix this problem, but it seems to me that perhaps it should be solved.

To be honest I don't even know if it will solve it, but it's a start!

> ave you tried to check the hash of the files is supplied in the cache? Maybe the files are corrupted in some way

Nope, and I'll tell you why: The cache system does not corrupt the `.deb` files, nor the `.pkg`/`.dmg`.
The only binary that has an issue is the Windows Setup one.
But, nonetheless, it maybe a good thing to actually experiment with a hash.

Thanks for the suggestion!!
I'll have a look into it once I get off my lazy arse and do the update of the current Stable version!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Y'all,

From the looks of it, the `/SP-` does not solve the issue :(

I've now disabled caching for windows all together.
I'm now a bit out of my depth since I don't know what else I should do in terms of debugging this.

Trying to build a personal runner would be a probability, but I don't mess with Windows any more :disappointed: 

I'll need some help from you peeps!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Y'all,

From my latest "_bang-my-head-against-a-wall_" trying to find a solution for am OPM package that has spaces in the path(The issue is with OPM data, not setup-lazarus) I'm beginning to suspect that the cache for macOS is also having some issues.

I'm not quite sure because I haven't dig into the problem to eliminate my own stupidity :smiley: 

I'll keep you posted when I have time to "_bang-my-head-against-a-wall_" on this particular development.

Cheers,
Gus

**Comment by vmaskmovps** [comment]
It seems to be a long-standing issue, I'll look into it and try to fix it in the rewrite. @gcarreno

**Comment by gcarreno** [comment]
Hey Stefan(@vmaskmovps),

Thanks !!

I have a slight suspicion that both the `.exe` and the `.dmg` are being damaged in the process of archival when cached. Alas, I don't have a way to prove it...

What baffles me the most is that the `.deb` is totally fine :shrug: 

Cheers,
Gus
